name: flutter_app
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  fluttertoast: ^8.2.5
  google_fonts: ^6.2.1
  flutter_svg:
  intl: ">=0.18.1 <0.20.0"

  flutter_native_splash: ^2.4.0

  http: ^1.2.1
  image_picker: ^1.1.1
  provider: ^6.1.2


dev_dependencies:
  dio: ^5.4.3+1
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
  - assets/vectors/
  - assets/images/
