# Generated by Django 5.0.5 on 2024-05-28 18:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='project/users/img'),
            preserve_default=False,
        ),
    ]
