# Generated by Django 5.0.5 on 2024-06-04 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_schedule_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='group_gender',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='group',
            name='max_age',
            field=models.PositiveSmallIntegerField(default=127),
        ),
        migrations.AddField(
            model_name='group',
            name='max_num',
            field=models.PositiveSmallIntegerField(default=127),
        ),
        migrations.AddField(
            model_name='group',
            name='min_age',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='group',
            name='min_num',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='group',
            name='current_num',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='group',
            name='flag',
            field=models.BooleanField(blank=True, default=0, null=True),
        ),
    ]
