# Generated by Django 5.0.5 on 2024-06-04 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_group_group_gender_group_max_age_group_max_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_img',
            field=models.ImageField(blank=True, null=True, upload_to='group/'),
        ),
    ]
