# Generated by Django 5.0.5 on 2024-06-05 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_groupstate_current_state_group_current_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='current_state',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
