# Generated by Django 5.0.5 on 2024-06-05 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_group_current_state'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GroupState',
            new_name='Member',
        ),
    ]
