# Generated by Django 5.0.5 on 2024-06-08 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_group_current_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variance',
            name='variable_time',
            field=models.CharField(max_length=26),
        ),
    ]
