# Generated by Django 5.0.5 on 2024-06-08 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_variance_variable_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstate',
            name='pos_leadership',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userstate',
            name='grade',
            field=models.PositiveSmallIntegerField(default=8),
        ),
    ]
