# Generated by Django 5.0.5 on 2024-06-08 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_rename_pos_leadership_userstate_pos_leadership_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='variance',
            name='day',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='variance',
            name='flag',
            field=models.BooleanField(blank=True, default=0, null=True),
        ),
    ]
