# Generated by Django 5.0.5 on 2024-06-11 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_remove_userstate_report_num_alter_schedule_timetable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstate',
            name='grade',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
