# Generated by Django 5.0.5 on 2024-06-11 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_alter_userstate_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variance',
            name='variable_time',
            field=models.CharField(max_length=29),
        ),
    ]
