# Generated by Django 5.0.5 on 2024-06-05 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_rename_waitmember_applymember'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmember',
            name='state',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='ApplyMember',
        ),
    ]
