# Generated by Django 5.0.5 on 2024-06-06 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_groupmember_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='current_state',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True),
        ),
    ]
