# Generated by Django 5.0.5 on 2024-06-08 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_userstate_pos_leadership_alter_userstate_grade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userstate',
            old_name='pos_leadership',
            new_name='pos_leadership_num',
        ),
    ]
